FROM openjdk:8-jre-alpine
ENV INGRID_USER=root
ENV RUN_DIRECTLY=true

ADD ingrid-iplug-*-installer.jar /

RUN unzip ingrid-iplug-*-installer.jar -d /tmp \
    && mkdir -p /opt/ingrid/ingrid-iplug-opensearch \
    && cp -R /tmp/ingrid-iplug-opensearch-*/* /opt/ingrid/ingrid-iplug-opensearch/ \
    && rm -Rf /tmp/* \
    && rm ingrid-*.jar

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /opt/ingrid/ingrid-iplug-opensearch/log.log
  # && ln -sf /dev/stderr /var/log/nginx/error.log

RUN touch /opt/ingrid/ingrid-iplug-opensearch/conf/config.override.properties
WORKDIR /opt/ingrid/ingrid-iplug-opensearch
EXPOSE 80

CMD /bin/sh start.sh start
